### ISSUE TITLE
How to init MySQL database? 如何初始化MySQL数据库？

### ISSUE THREAD

**Issue by rise0chen** [codetrial/got-auth-service#1]
Can you share the backup file of MySQL? 您可以分享一下MySQL的备份文件吗？

**Comment by felixpy** [comment]
I'll add it to this repo today.

**Comment by felixpy** [comment]
Hi, @rise0chen . I have added the initial file of SQL, please see if it helps, thank you! 165066c00bb19ad7ac8a37738fda8b64abac8ae8

**Comment by rise0chen** [comment]
I see it in [https://github.com/codetrial/got-auth-service/blob/develop/data/gotauth.sql](https://github.com/codetrial/got-auth-service/blob/develop/data/gotauth.sql). 
thanks
